server:
  port: 81

spring:
  application:
    name: courier-order-service

eureka:
  client:
    # means whether to register itself in Eureka Server, the default is true
    register-with-eureka: true

    # means whether to fetch data from Eureka Server, the default is true.
    # Single node mode doesn't matter but cluster must be set to true to work with ribbon.
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: order81
    prefer-ip-address: true